### ISSUE TITLE
Cannot install plugins using components built with outdated Qt 5.7

### ISSUE THREAD

**Issue by JimmyMac3** [dorianmuthig/obs-studio-ftl#1]
I was super excited when I saw this - Thank you so much for your effort in compiling this. I been running it for a week now and it is rock solid and working great.

Reference Issue - [https://github.com/mixer/obs-studio-ftl/issues/52](https://github.com/mixer/obs-studio-ftl/issues/52)
Refrence Plugin - [https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/](https://obsproject.com/forum/resources/obs-websocket-remote-control-of-obs-studio-made-easy.466/)

The only issue I'm having is if a plugin for OBS-Studio uses the QuickTime repo (Webscoket Plugin Above) It won't work with this build or with the Mixer OBS-Studio-FTL latest build either. This is because Mixer compiled its latest build with QT 5.8 (which was the latest QT at the time) and after looking at this 19.0.2-FTL build it was compiled with QT 5.9

Problem is still to this day the OFFICIAL OBS-Studio 19.0.2 and 18.0.1 are both compiled with QT 5.7 and the plugin makers are writing their plugins compatible with QT 5.7 only. In other words all the FTL forks are not compatible with the OBS Plugins out there. When I saw that you did this I was hoping that you would have fix the mistake that Mixer made and used the exact same versions of the dependencies that are in the official build.

Is there anyway you could recompile this with QT 5.7 so it matches more exact to the official OBS-Studio 19.0.2 please? I know I'm not the only one waiting for Mixer or someone to fix this mistake/bug and make it so the OBS-Webscoket Plugin works with the FTL version of OBS. Thanks

**Comment by dori4n** [comment]
Actually Qt isn't QuickTime, but the framework used by OBS to display the graphical user interface. It was compiled with Qt version 5.9 on purpose, because the older versions have issues on Windows 10. There is no mistake. The plugins can be built with Qt 5.9 also. I will look into doing that instead. Do you have any other plugins you like to use?

For the time being you can try this alpha build that was built on the OBS project's continuous integration build system https://github.com/mixer/obs-studio-ftl/releases/download/v1.0.0/OBS-Studio-19.0.3-FTL-Full-Installer.exe

**Comment by JimmyMac3** [comment]
I have confirmed the new Alpha OBS-FTL is compatible with the OBS Websocket plugin :)
